### ISSUE TITLE
More precise naming convention?

### ISSUE THREAD

**Issue by camrinbraun** [ocean-tracking-network/biologging_standardization#5]
I'm coercing the example data to the templates we've generated but wondering if we need more precise metadata and observation variable names. For example, "Deployment date and time" (as in [here](https://github.com/ocean-tracking-network/biologging_standardization/blob/master/templates/deployment-metadata.md)) is not a particularly friendly name for that metadata variable. Instead, shouldn't we use something like "deployment_time_start" (as in [here](https://github.com/tagbase/tagbase/blob/master/eTagMetadataInventory.csv))? Is there a reason we have it the way it is now which is quite human readable but perhaps not ideal for machine-to-machine (i.e. some convention)?

**Comment by peggynewman** [comment]
I totally agree. I would encourage using **camelCase** convention for readability. 
There's a naming convention I'm partial to that advises structuring variables as subject-modifier-class, where **class** indicates the type of data eg. date, number, name, description, code
Then **subject-modifier** becomes a bit easier to split out. That way when you're looking at all the variables for deployment for example, they would end up being grouped together if alphabetically sorted: 
eg. deploymentStartTime, deploymentEndTime

Because even in the act of publishing to Github we've already needed these variables to be machine readable - I needed names that didn't have spaces to name the files. So I've already partially implemented this. If we think this naming convention is ok I can do a large scale update on all of the pages to add them.

**Comment by SequeiraLab** [comment]
I agree as well. Peggy your suggestion seems good and having the variables all listed in a group will be helpful.

**Comment by jdpye** [comment]
From our get-together this evening: We're going to work from the camelCase already used in the naming of the files in the fields/ subfolder, and the templates will show those names shortly.

**Comment by camrinbraun** [comment]
these look pretty much done by @peggynewman, i just made a few minor fixes (https://github.com/ocean-tracking-network/biologging_standardization/commit/49b8bbbd73563fbcb6d0f30fcb35e0b21b8957b2) as i worked through the blue shark example
